version: "3.8"

services:
  hooks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workflows
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
    command: >
      sh -c "
        sleep 5 &&
        npx prisma generate &&
        npm run dev
      "
    networks:
      - workflows-network
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - workflows-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  workflows-network:
    external: true
    name: workflows-network
