version: "3.8"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workflows
      - PORT=8000
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
    command: >
      sh -c "
        sleep 5 &&
        npx prisma generate &&
        npm run dev
      "
    networks:
      - workflows-network
    restart: unless-stopped

networks:
  workflows-network:
    external: true
    name: workflows-network